import os

BOT_TOKEN = os.getenv("BOT_TOKEN")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
DATABASE_URL = os.getenv("DATABASE_URL")
ADMIN_ID = int(os.getenv("ADMIN_ID", 0))

SUBSCRIPTION_PRICE_UZS = int(os.getenv("SUBSCRIPTION_PRICE_UZS", "35000"))
SUBSCRIPTION_DURATION_DAYS = int(os.getenv("SUBSCRIPTION_DURATION_DAYS", "30"))
CARD_NUMBER = os.getenv("CARD_NUMBER", "")

FREE_DAILY_LIMIT = int(os.getenv("FREE_DAILY_LIMIT", "3"))
PAID_DAILY_LIMIT = int(os.getenv("PAID_DAILY_LIMIT", "30"))
